language: c
env:
 global:
   - DONT_FETCH_GAP_JULIA_PKG=yes
   - JULIAROOT=$TRAVIS_BUILD_DIR/julia
   - GAPROOT=$TRAVIS_BUILD_DIR/gap
   - MAKEFLAGS="-j4"
   - JULIA_TRACK_COVERAGE=yes

addons:
  apt_packages:
    - libgmp-dev
    - libreadline-dev
    - zlib1g-dev

branches:
  only:
    - master

before_script:
  - printenv | sort
  - git show --pretty=fuller -s
  - mkdir -p coverage
  - etc/install_julia_gap.sh
  - ln -s $TRAVIS_BUILD_DIR/JuliaInterface $GAPROOT/pkg/
  - ln -s $TRAVIS_BUILD_DIR/JuliaExperimental $GAPROOT/pkg/
  - ln -s $TRAVIS_BUILD_DIR/LibGAP.jl $GAPROOT/pkg/
  - etc/travis_build.sh

script:
  - etc/travis_test.sh

after_script:
  - cd $TRAVIS_BUILD_DIR
  - $GAPROOT/gap --quitonbreak --norepl etc/gather_coverage.g
  - ${JULIAROOT}/bin/julia etc/gather_coverage.jl
  - bash <(curl -s https://codecov.io/bash)
